### ISSUE TITLE
Creating a new file not possible

### ISSUE THREAD

**Issue by JanWerder** [superpowers/superpowers-love2d#1]
Hey,

I compiled the editor from source but can't seem to create my main.lua.
When I click the Lua script pane in the lower left, it just says "File not found"

![Screenshot](http://i.imgur.com/QFFQFLN.png)

**Comment by bilou84** [comment]
There is a submodule along with this system. https://github.com/superpowers/superpowers-common-plugins/tree/master

Have you used the command `git submodule update --init` to initialize it ?

**Comment by JanWerder** [comment]
I ran `git submodule update --init` in the `superpowers\systems\subGame` folder.
The result is that I have the repo you described in the `superpowers\systems\subGame\plugins\common` folder. Is that correct?

**Comment by bilou84** [comment]
You have to do the same for the love2d system. Both systems are completely unrelated.

**Comment by JanWerder** [comment]
still the same, I ran `git submodule update --init` on both folders in `superpowers\systems\`

**Comment by bilou84** [comment]
After that, you will have to restart the build command.
Doing `npm run build love2d` will only rebuild the love system, if your system folder name is "love2d".

**Comment by JanWerder** [comment]
Ah ok, my bad. Works now

**Comment by bilou84** [comment]
Great :+1:
