### ISSUE TITLE
There's no apply button for script drafts.

### ISSUE THREAD

**Issue by Yukitty** [superpowers/superpowers-love2d#4]
Currently, it appears you _have_ to press the keyboard shortcut `Ctrl+S` to save a draft Lua script, since there is no TypeScript compiler window to click an apply button in.

At some point there should be _some_ kind of GUI button for that again, somewhere.

**Comment by elisee** [comment]
Indeed. Should be pretty easy to port over from Superpowers Game if anyone is up for it!
