### ISSUE TITLE
Looking for love loop

### ISSUE THREAD

**Issue by Bottersnike** [superpowers/superpowers-love2d#6]
I've lust downloaded superpowers and built it with love2d but when I try to run a game I have the screen "looking for love" stuck and occasionally it will go blank and the error:
7419:0530/104052:ERROR:CONSOLE(0) "the given range isn't in document."
And then a long link printed in the terminal that I ran "npm run start" from. I really hope you can fix this soon as I was looking forwards to being able to use love in superpowers

**Comment by elisee** [comment]
Hi!

What OS are you running it on?

**Comment by Bottersnike** [comment]
I'm running it on Linux. Which love prints "/usr/bin/love". As a side note, when it says looking for love, it doesn't then show the button to find love manually to the message to go and install it,

**Comment by Bottersnike** [comment]
I'm running Linux(raspbian). Node.js version 5.11.1. "which love" prints "/usr/bin/love". As a side note, the looking for love page doesn't go on to show the manual search button or the message with a link to download love.

**Comment by elisee** [comment]
Are there errors in the devtools console? You can open it with F12 while the player window is focused.

**Comment by Bottersnike** [comment]
The console of the editor shows no errors, but I can't even start the devtools in the player. The only thing I can do in the player is quit

P.S. It might be my build because I just ran superpowers on my windows 10 box and it seemed to get stuck at "Building...". Is there anywhere that I can download a prebuilt love2d superpowers (Ideally an npm one so I can run it on Linux)?

**Comment by elisee** [comment]
Closing since new versions with a different mechanism for running LÖVE have been released.
